2023-08-09 21:01:14,241 - INFO - Serving on http://0.0.0.0:5007
2023-08-09 21:06:43,088 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 00:49:17,932 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 00:59:15,721 - INFO - Validation time: 3.994 seconds
2023-08-12 00:59:15,725 - INFO - POST /forward_to_Order
2023-08-12 00:59:15,728 - INFO - Validation time: 4.001 seconds
2023-08-12 00:59:15,728 - INFO - Execution time: 4.005 seconds
2023-08-12 01:00:15,376 - INFO - POST /forward_to_Order
2023-08-12 01:00:15,376 - INFO - Validation time: 0.000 seconds
2023-08-12 01:00:15,376 - INFO - Execution time: 0.000 seconds
2023-08-12 01:02:48,100 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:02:58,464 - INFO - Validation time: 2.063 seconds
2023-08-12 01:02:58,464 - INFO - POST /forward_to_Order
2023-08-12 01:02:58,464 - ERROR - issue with processing 'SQLOrmService' object is not callable
2023-08-12 01:02:58,464 - INFO - Validation time: 2.063 seconds
2023-08-12 01:02:58,465 - INFO - Execution time: 2.063 seconds
2023-08-12 01:02:58,465 - ERROR - Exception on /forward_to_Order [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'forward_to_Order' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-12 01:05:10,538 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:05:20,146 - INFO - Validation time: 2.052 seconds
2023-08-12 01:05:20,146 - INFO - POST /forward_to_Order
2023-08-12 01:05:20,146 - ERROR - issue with processing 'SQLOrmService' object is not callable
2023-08-12 01:05:20,146 - INFO - Validation time: 2.052 seconds
2023-08-12 01:05:20,147 - INFO - Execution time: 2.052 seconds
2023-08-12 01:05:20,147 - ERROR - Exception on /forward_to_Order [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'forward_to_Order' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-12 01:27:12,431 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:27:21,070 - INFO - Validation time: 2.155 seconds
2023-08-12 01:28:08,340 - INFO - Validation time: 0.007 seconds
2023-08-12 01:28:08,341 - INFO - POST /forward_to_Order
2023-08-12 01:28:08,341 - ERROR - issue with processing 'SQLOrmService' object is not callable
2023-08-12 01:28:08,341 - INFO - Validation time: 0.008 seconds
2023-08-12 01:28:08,341 - INFO - Execution time: 0.008 seconds
2023-08-12 01:28:08,341 - ERROR - Exception on /forward_to_Order [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'forward_to_Order' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-12 01:32:17,437 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:32:58,917 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:33:08,697 - INFO - Validation time: 2.037 seconds
2023-08-12 01:33:08,697 - INFO - POST /forward_to_Order
2023-08-12 01:33:08,697 - INFO - order generation function triggered..
2023-08-12 01:33:08,697 - INFO - checking if table exist!!...
2023-08-12 01:33:08,886 - INFO - session closed
2023-08-12 01:33:08,917 - INFO - Validation time: 2.037 seconds
2023-08-12 01:33:08,917 - INFO - Execution time: 2.258 seconds
2023-08-12 01:37:04,122 - INFO - Validation time: 2.033 seconds
2023-08-12 01:37:04,122 - INFO - POST /forward_to_Order
2023-08-12 01:37:04,122 - INFO - order generation function triggered..
2023-08-12 01:37:04,122 - INFO - checking if table exist!!...
2023-08-12 01:37:04,132 - INFO - session closed
2023-08-12 01:37:04,133 - INFO - Validation time: 2.033 seconds
2023-08-12 01:37:04,133 - INFO - Execution time: 2.044 seconds
2023-08-12 01:37:14,019 - INFO - POST /forward_to_Order
2023-08-12 01:37:14,020 - INFO - order generation function triggered..
2023-08-12 01:37:14,020 - INFO - checking if table exist!!...
2023-08-12 01:37:14,060 - INFO - session closed
2023-08-12 01:37:14,061 - INFO - Validation time: 0.000 seconds
2023-08-12 01:37:14,061 - INFO - Execution time: 0.042 seconds
2023-08-12 01:39:49,358 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:40:00,608 - INFO - Validation time: 2.037 seconds
2023-08-12 01:40:54,083 - INFO - Validation time: 0.006 seconds
2023-08-12 01:40:54,084 - INFO - POST /forward_to_Order
2023-08-12 01:40:54,084 - INFO - order generation function triggered..
2023-08-12 01:40:54,084 - INFO - checking if table exist!!...
2023-08-12 01:40:54,119 - INFO - session closed
2023-08-12 01:40:54,122 - INFO - Validation time: 0.006 seconds
2023-08-12 01:40:54,123 - INFO - Execution time: 0.045 seconds
2023-08-12 01:41:34,578 - INFO - Serving on http://0.0.0.0:5007
2023-08-12 01:41:44,060 - INFO - Validation time: 2.041 seconds
2023-08-12 01:41:44,060 - INFO - POST /forward_to_Order
2023-08-12 01:41:44,060 - INFO - order generation function triggered..
2023-08-12 01:41:44,060 - INFO - checking if table exist!!...
2023-08-12 01:41:44,110 - INFO - session closed
2023-08-12 01:41:44,115 - INFO - Validation time: 2.041 seconds
2023-08-12 01:41:44,115 - INFO - Execution time: 2.096 seconds
2023-08-12 01:45:30,123 - INFO - Validation time: 2.034 seconds
2023-08-12 01:45:30,123 - INFO - POST /forward_to_Order
2023-08-12 01:45:30,123 - INFO - order generation function triggered..
2023-08-12 01:45:30,123 - INFO - checking if table exist!!...
2023-08-12 01:45:30,132 - INFO - session closed
2023-08-12 01:45:30,132 - INFO - Checkout Item found....
2023-08-12 01:45:30,132 - INFO - checking if table exist!!...
2023-08-12 01:45:30,154 - INFO - session closed
2023-08-12 01:45:30,155 - INFO - Validity test passed !!!
2023-08-12 01:45:30,155 - INFO - checking if table exist!!...
2023-08-12 01:45:30,160 - INFO - SELECT COUNT(*) from external.tbl_order WHERE uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='ghsgdhsh7873673hwgdhll-jkj-'and payment_status=0;
2023-08-12 01:45:30,170 - INFO - session closed
2023-08-12 01:45:30,170 - INFO - inserting
2023-08-12 01:45:30,170 - INFO - checking if table exist!!...
2023-08-12 01:45:30,176 - INFO - row inserted!..
2023-08-12 01:45:30,183 - INFO - session closed
2023-08-12 01:45:30,183 - INFO - new
2023-08-12 01:45:30,183 - INFO - Validation time: 2.034 seconds
2023-08-12 01:45:30,183 - INFO - Execution time: 2.094 seconds
2023-08-12 01:46:24,354 - INFO - POST /forward_to_Order
2023-08-12 01:46:24,354 - INFO - order generation function triggered..
2023-08-12 01:46:24,354 - INFO - checking if table exist!!...
2023-08-12 01:46:24,363 - INFO - session closed
2023-08-12 01:46:24,363 - INFO - Checkout Item found....
2023-08-12 01:46:24,363 - INFO - checking if table exist!!...
2023-08-12 01:46:24,393 - INFO - session closed
2023-08-12 01:46:24,394 - INFO - Validity test passed !!!
2023-08-12 01:46:24,394 - INFO - checking if table exist!!...
2023-08-12 01:46:24,398 - INFO - SELECT COUNT(*) from external.tbl_order WHERE uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='ghsgdhsh7873673hwgdhll-jkj-'and payment_status=0;
2023-08-12 01:46:24,421 - INFO - session closed
2023-08-12 01:46:24,421 - INFO - updating the table
2023-08-12 01:46:24,421 - INFO - checking if table exist!!...
2023-08-12 01:46:24,453 - INFO - row inserted!..
2023-08-12 01:46:24,464 - INFO - session closed
2023-08-12 01:46:24,465 - INFO - new
2023-08-12 01:46:24,465 - INFO - Validation time: 0.000 seconds
2023-08-12 01:46:24,465 - INFO - Execution time: 0.111 seconds
